#ifndef _NOTEPAD_RESOURCES_H
#define _NOTEPAD_RESOURCES_H

#include "std.h"

#define NOTEPAD_IDI_BIG    1
#define NOTEPAD_IDI_MEDIUM 2
#define NOTEPAD_IDI_SMALL  3

#define NOTEPAD_IDI_EXE      NOTEPAD_IDI_BIG
#define NOTEPAD_IDI_TITLEBAR NOTEPAD_IDI_SMALL
#define NOTEPAD_IDI_TASKBAR  NOTEPAD_IDI_MEDIUM

#define NOTEPAD_IDR_MENU          1
#define NOTEPAD_IDR_FONT_CONSOLAS 2

#define NOTEPAD_MENUITEM_EXIT              1
#define NOTEPAD_MENUITEM_TOGGLE_STATUSBAR  2
#define NOTEPAD_MENUITEM_DUMP_TEXTURES     3

#endif /* _NOTEPAD_RESOURCES_H */
